# Generated by Django 6.0.1 on 2026-06-20 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0007_rename_cart_item_cart_id_content_cart_item_cart_id_2d9eff_idx_and_more'),
        ('postcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityDiscount',
            fields=[
            ],
            options={
                'ordering': ['-min_cart_value'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cart.discount',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postcards.gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='shop.shop')),
            ],
        ),
    ]
