# Generated by Django 6.0.1 on 2026-06-28 17:58

import django.db.models.deletion
import miaiqi_cards.website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0001_initial'),
        ('shop', '0001_initial'),
        ('simple_page', '0001_initial'),
        ('website', '0003_delete_shopsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=100)),
                ('order_text', models.TextField(blank=True)),
                ('checkout_text', models.TextField(blank=True)),
                ('confirmation_text', models.TextField(blank=True)),
                ('gallery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postcards.gallery')),
            ],
            bases=(miaiqi_cards.website.models.SectionMixin, 'simple_page.section'),
        ),
        migrations.AlterField(
            model_name='price',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prices', to='shop.shopsection'),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
