# Generated by Django 6.0.1 on 2026-06-29 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0002_remove_gallery_postcards_gallerysection_and_more'),
        ('shop', '0002_shopsection_alter_price_shop_delete_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopsection',
            name='gallery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postcards.gallerysection'),
        ),
    ]
