# Generated by Django 6.0.1 on 2026-06-20 07:17

import django.db.models.deletion
import reorder_items_widget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='postcards/')),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'website_postcard',
            },
        ),
        migrations.CreateModel(
            name='GalleryPostcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', reorder_items_widget.models.ReorderItemsField(blank=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postcards.gallery')),
                ('postcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postcards.postcard')),
            ],
            options={
                'unique_together': {('gallery', 'postcard')},
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='postcards',
            field=models.ManyToManyField(related_name='galleries', through='postcards.GalleryPostcard', to='postcards.postcard'),
        ),
    ]
