# Generated by Django 6.0.1 on 2026-06-29 10:12

import django.db.models.deletion
import miaiqi_cards.website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0001_initial'),
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='postcards',
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('postcards', models.ManyToManyField(related_name='galleries', through='postcards.GalleryPostcard', to='postcards.postcard')),
            ],
            bases=(miaiqi_cards.website.models.SectionMixin, 'simple_page.section'),
        ),
        migrations.AlterField(
            model_name='gallerypostcard',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postcards.gallerysection'),
        ),
    ]
