# Generated by Django 6.0.1 on 2026-06-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0002_remove_gallery_postcards_gallerysection_and_more'),
        ('shop', '0003_alter_shopsection_gallery'),
        ('website', '0004_delete_gallerysection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
