# Generated by Django 6.0.1 on 2026-07-28 12:27

import miaiqi_cards.postcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0003_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('original', models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to=miaiqi_cards.postcards.models.upload_original)),
                ('large', models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to=miaiqi_cards.postcards.models.upload_large)),
                ('medium', models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to=miaiqi_cards.postcards.models.upload_medium)),
                ('small', models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to=miaiqi_cards.postcards.models.upload_small)),
            ],
        ),
    ]
