# Generated by Django 6.0.1 on 2026-07-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0003_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(upload_to='postcards/')),
                ('large', models.ImageField(upload_to='postcards/')),
                ('medium', models.ImageField(upload_to='postcards/')),
                ('small', models.ImageField(upload_to='postcards/')),
            ],
        ),
    ]
