# Generated by Django 6.0.1 on 2026-07-29 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcard',
            name='image',
        ),
        migrations.AddField(
            model_name='postcard',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcard', to='postcards.image'),
        ),
    ]
