# Generated by Django 6.0.1 on 2026-07-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0004_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
