# Generated by Django 6.0.1 on 2026-09-16 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0005_alter_postcard_image'),
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostcardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.page')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('simple_page.page',),
        ),
    ]
