# Generated by Django 6.0.1 on 2026-07-28 08:34

import miaiqi_cards.postcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0005_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large',
            field=models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to='postcards/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium',
            field=models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to='postcards/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to='postcards/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='small',
            field=models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to='postcards/'),
        ),
    ]
