# Generated by Django 6.0.1 on 2026-07-28 10:14

import miaiqi_cards.postcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcards', '0006_alter_image_large_alter_image_medium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='large',
            field=models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to=miaiqi_cards.postcards.models.upload_large),
        ),
        migrations.AlterField(
            model_name='image',
            name='medium',
            field=models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to=miaiqi_cards.postcards.models.upload_medium),
        ),
        migrations.AlterField(
            model_name='image',
            name='original',
            field=models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to=miaiqi_cards.postcards.models.upload_original),
        ),
        migrations.AlterField(
            model_name='image',
            name='small',
            field=models.ImageField(storage=miaiqi_cards.postcards.models.OverwriteStorage(), upload_to=miaiqi_cards.postcards.models.upload_small),
        ),
    ]
