# Generated by Django 6.0.1 on 2026-06-13 10:01

import django.db.models.deletion
import miaiqi_cards.website.models
import reorder_items_widget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('body', models.TextField(blank=True)),
            ],
            bases=('simple_page.section',),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            bases=(miaiqi_cards.website.models.CSSMixin, 'simple_page.section'),
        ),
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='postcards/')),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
            ],
            bases=(miaiqi_cards.website.models.CSSMixin, 'simple_page.section'),
        ),
        migrations.CreateModel(
            name='MiaiqiCardsPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('simple_page.page',),
        ),
        migrations.CreateModel(
            name='GalleryPostcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', reorder_items_widget.models.ReorderItemsField(blank=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.gallery')),
                ('postcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.postcard')),
            ],
            options={
                'unique_together': {('gallery', 'postcard')},
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='postcards',
            field=models.ManyToManyField(related_name='galleries', through='website.GalleryPostcard', to='website.postcard'),
        ),
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('postcard_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_postcard', to='simple_page.section')),
                ('postcards', models.ManyToManyField(to='website.postcard')),
                ('subtitle_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_subtitle', to='simple_page.section')),
                ('title_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_title', to='simple_page.section')),
            ],
            bases=(miaiqi_cards.website.models.CSSMixin, 'simple_page.section'),
        ),
    ]
