# Generated by Django 6.0.1 on 2026-06-20 07:17

import django.db.models.deletion
import miaiqi_cards.website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postcards', '0001_initial'),
        ('shop', '0001_initial'),
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('body', models.TextField(blank=True)),
            ],
            bases=('simple_page.section',),
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
            ],
            bases=(miaiqi_cards.website.models.SectionMixin, 'simple_page.section'),
        ),
        migrations.CreateModel(
            name='MiaiqiCardsPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('simple_page.page',),
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='postcards.gallery')),
            ],
            bases=(miaiqi_cards.website.models.SectionMixin, 'simple_page.section'),
        ),
        migrations.CreateModel(
            name='ShopSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True)),
                ('shop', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shop')),
            ],
            bases=(miaiqi_cards.website.models.SectionMixin, 'simple_page.section'),
        ),
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('postcard_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_postcard', to='simple_page.section')),
                ('postcards', models.ManyToManyField(to='postcards.postcard')),
                ('subtitle_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_subtitle', to='simple_page.section')),
                ('title_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_title', to='simple_page.section')),
            ],
            bases=(miaiqi_cards.website.models.SectionMixin, 'simple_page.section'),
        ),
    ]
