# Generated by Django 6.0.1 on 2026-06-27 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0001_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomesection',
            name='postcard_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_postcard', to='simple_page.section'),
        ),
        migrations.AlterField(
            model_name='welcomesection',
            name='subtitle_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_subtitle', to='simple_page.section'),
        ),
        migrations.AlterField(
            model_name='welcomesection',
            name='title_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_title', to='simple_page.section'),
        ),
    ]
