# Generated by Django 6.0.1 on 2026-06-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_welcomesection_postcard_ref_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopSection',
        ),
    ]
