# Generated by Django 6.0.1 on 2026-06-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delete_shopsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GallerySection',
        ),
    ]
