# Generated by Django 6.0.1 on 2026-08-04 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_page', '0001_initial'),
        ('website', '0004_delete_gallerysection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiaiqiCardsPage',
        ),
        migrations.CreateModel(
            name='MiaiqiCardsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.page')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('simple_page.page',),
        ),
    ]
