# Generated by Django 6.0.1 on 2026-08-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_delete_miaiqicardspage_miaiqicardspage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WelcomeSection',
        ),
    ]
