# Generated by Django 6.0.1 on 2026-06-04 16:54

import miaiqi_cards_app.models
import django.db.models.deletion
import markdownx.models
import reorder_items_widget.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simple_page', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('body', markdownx.models.MarkdownxField(blank=True)),
            ],
            bases=('simple_page.section',),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=100)),
                ('description', markdownx.models.MarkdownxField(blank=True)),
            ],
            bases=(miaiqi_cards_app.models.CSSMixin, 'simple_page.section'),
        ),
        migrations.CreateModel(
            name='MiaiqiCardsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.page')),
                ('subtitle', models.CharField(max_length=255)),
                ('background_image', models.ImageField(upload_to='backgrounds/')),
            ],
            options={
                'abstract': False,
            },
            bases=('simple_page.page',),
        ),
        migrations.CreateModel(
            name='Postcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', markdownx.models.MarkdownxField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='postcards/')),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=255)),
                ('body', markdownx.models.MarkdownxField(blank=True)),
            ],
            bases=(miaiqi_cards_app.models.CSSMixin, 'simple_page.section'),
        ),
        migrations.CreateModel(
            name='GalleryPostcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', reorder_items_widget.models.ReorderItemsField(blank=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaiqi_cards_app.gallery')),
                ('postcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miaiqi_cards_app.postcard')),
            ],
            options={
                'unique_together': {('gallery', 'postcard')},
            },
        ),
        migrations.AddField(
            model_name='gallery',
            name='postcards',
            field=models.ManyToManyField(related_name='galleries', through='miaiqi_cards_app.GalleryPostcard', to='miaiqi_cards_app.postcard'),
        ),
    ]
