# Generated by Django 6.0.1 on 2026-06-11 14:35

import django.db.models.deletion
import miaiqi_cards_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miaiqi_cards_app', '0001_initial'),
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('postcard_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_postcard', to='simple_page.section')),
                ('postcards', models.ManyToManyField(to='miaiqi_cards_app.postcard')),
                ('subtitle_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_subtitle', to='simple_page.section')),
                ('title_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welcome_title', to='simple_page.section')),
            ],
            bases=(miaiqi_cards_app.models.CSSMixin, 'simple_page.section'),
        ),
        migrations.DeleteModel(
            name='MiaiqiCardsPage',
        ),
        migrations.CreateModel(
            name='MiaiqiCardsPage',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('simple_page.page',),
        ),
    ]
