# Generated by Django 6.0.1 on 2026-08-10 15:49

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postcards', '0005_alter_postcard_image'),
        ('simple_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('section_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simple_page.section')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('postcard_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_postcard', to='simple_page.section')),
                ('subtitle_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_subtitle', to='simple_page.section')),
                ('title_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_title', to='simple_page.section')),
            ],
            bases=('simple_page.section',),
        ),
        migrations.CreateModel(
            name='WelcomeTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('h1_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('h1_bg_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('h2_bg_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('img_bg_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None)),
                ('postcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='postcards.postcard')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='welcome.welcomesection')),
            ],
        ),
    ]
